---
title: "Untitled"
format: html
---


## ¿Irá Ud. a votar en las próximas elecciones presidenciales de 2017?

CEP N°78 (Noviembre-Diciembre 2016) se pregunta por primera vez elecciones presidenciales de 2017 (escala 1 a 4; Si, probablemente, probablemente no, No). Antes de esto, solo se pregunta voto retrospectivo a 2013.

CEP N 79 (abril-mayo 2017)

CEP N 80 (julio-agosto 2017)

CEP N 81 (Septiembre-Octubre 2017)



## ¿Votó Ud. en la pasada elección presidencial y parlamentaria de noviembre de 2017?

CEP N 82 (Octubre-Noviembre 2018) se pregunta por primera vez si votó en la elección pasada de presidencial y parlamentaria de 2017 (escala 1 a2; si y no)

CEP N 83 (abril-junio 2019) ¿Votó Ud. en la pasada elección presidencial y parlamentaria de noviembre de 2017?

CEP N 84 (Noviembre 2019-enero 2020) ¿Votó Ud. en la pasada elección presidencial y parlamentaria de noviembre de 2017?

##

CEP N 85 (Agosto 2021) Elección pasada Plebiscito (Si; no) Votó Ud. en el plebiscito sobre una nueva constitución realizado en octubre del año pasado?

CEP N 85 (Agosto 2021) Elección pasada convencionales, municipales, GR (Si; no)


CEP N 86 (Abril - Mayo 2022) ¿Votó Ud. En la 1ra vuelta de la elección presidencial de noviembre del año pasado?


CEP N 86 (Abril - Mayo 2022) ¿Votó Ud. en la 2da vuelta de la elección presidencial de diciembre del año pasado?



CEP N 88 (Noviembre - Diciembre 2022) El 4 de septiembre del 2022 se realizó el plebiscito de salida sobre la propuesta de Nueva Constitución. ¿Votó Ud. en esa elección?

CEP N 88 (Noviembre - Diciembre 2022) ¿Votó Ud. en el plebiscito sobre una nueva constitución realizado en octubre del 2020?

CEP N 88 (Noviembre - Diciembre 2022) ¿Votó Ud. en la 1ra vuelta de la elección presidencial de noviembre del 2021?

CEP N 88 (Noviembre - Diciembre 2022) ¿Votó Ud. en la pasada elección presidencial de diciembre de 2021?



CEP N 89 (Junio - Julio 2023) ¿Votó Ud. en la 2da vuelta de la elección presidencial de diciembre de 2021?

CEP N 89 (Junio - Julio 2023) El 4 de septiembre del 2022 se realizó el plebiscito de salida sobre la propuesta de Nueva Constitución. ¿Votó Ud. en esa elección?

CEP N 89 (Junio - Julio 2023) El 7 de mayo de este año se realizaron las elecciones para consejeros constitucionales. ¿Votó Ud. en esa elección?




CEP N 90 (Septiembre - Octubre 2023) ¿Votó Ud. en la 2da vuelta de la elección presidencial de diciembre de 2021?

CEP N 90 (Septiembre - Octubre 2023) El 4 de septiembre del 2022 se realizó el plebiscito de salida sobre la propuesta de Nueva Constitución. ¿Votó Ud. en esa elección?

CEP N 90 (Septiembre - Octubre 2023) El 7 de mayo de este año se realizaron las elecciones para consejeros constitucionales. ¿Votó Ud. en esa elección?




CEP N 91 (Junio - Julio 2024) ¿Votó Ud. en la 2da vuelta de la elección presidencial de diciembre de 2021?

CEP N 92 (Agosto - Septiembre 2024) ¿Votó Ud. en la 2da vuelta de la elección presidencial de diciembre de 2021?



CEP N 93 (Marzo - Abril 2025) ¿Votó Ud. en la 2da vuelta de la elección presidencial de diciembre de 2021?



CEP N 94 (Mayo-Junio 2025) ¿Votó Ud. en la 2da vuelta de la elección presidencial de diciembre de 2021?


CEP N 95 (Septiembre-Octubre 2025) ¿Votó usted en la 2da vuelta de la elección presidencial de diciembre de 2021?

CEP N 95 (Septiembre-Octubre 2025) ¿irá usted a votar en las próximas elecciones presidenciales de 2025?

```{r}
cep_consolidada <-
    readRDS("base_consolidada_2010_2026_23062026.rds")


sjmisc::frq(cep_consolidada$elec_part_38)


```